export const dataGeo = {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        properties: {
          ID: 1,
          isAlien: "yes",
          name: "Marda Loop Community Association",
          img: "src/images/halls/communityhall1.jpg",
          address: "3130 - 16th Street SW Calgary, AB T2T 4G7, Canada",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1011762, 51.0256322],
        },
        communityAssociationInformation: {
          facilityEmail: "N/A",
          communityAssociationWebsite: "mardaloop.com",
          facilityFaxNumber: "(403) 228-3643",
          federalCharityStatusRegistered: "No",
          facilityLocatedat: "3130 - 16 Street SW",
          provincialSocietyRegisteredName: "Marda Loop Community Association",
          facilityPhoneNumber: "(403) 244-5411",
          provincialSocietyRegisteredDate: "21069",
        },
        recreationAmenities: {
          sportsPlayfields: "Yes",
          skatingRink: "Yes – Outdoor",
          tennisCourts: "Yes",
          swimmingPool: "Yes – Outdoor",
          other: "Beach Volleyball Courts",
          hockeyRink: "Yes",
        },
        communityAssociationName: "Marda Loop Community Association",
        communityAssociationFacilities: {
          soundSystem: "Yes",
          lounge: "No",
          mainHallLicensedCapacity: "220",
          kitchen: "Yes – Commercial",
          stage: "Yes",
          gamesRoom: "No",
          indoorFireplace: "Yes",
          meetingRooms: "Yes",
          gym: "No",
          wheelchairAccess: "Yes",
          outdoorBBQ: "Yes",
        },
        communityAssociationBoundaries: {
          east: "14 Street (including River Park and Sandy Beach); Elbow River",
          south: "50 Avenue",
          north: "33 Avenue; 20 Street; 26 Avenue",
          west: "Crowchild Trail",
        },
        cityQuadrant: "SW",
        programs: {
          bingo: "No",
          dance: "Yes",
          artClasses: "N/A",
          sports: "Yes",
          childCare: "No",
          fitness: "No",
          seniorsProgram: "No",
          youthJustice: "No",
        },
      },
  
      {
        type: "Feature",
        properties: {
          ID: 2,
          isAlien: "",
          name: "Strathcona Christie Aspen Community Association",
          img: "src/images/halls/CH2.jpeg",
          address: "277 Strathcona Dr SW, Calgary, AB T3H 2A4, Canada",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        communityAssociationBoundaries: {
          east: "Sarcee Trail",
          north: "Bow Trail",
          south: "17 Avenue",
          west: "Stoney Trail R.O.W.",
        },
        communityAssociationFacilities: {
          soundSystem: "Yes",
          kitchen: "Yes – Commercial",
          gym: "Yes",
          gamesRoom: "No",
          lounge: "Yes",
          mainHallLicensedCapacity: "240",
          indoorFireplace: "Yes",
          wheelchairAccess: "No",
          meetingRooms: "Yes",
          stage: "Yes",
          outdoorBBQ: "No",
        },
        programs: {
          bingo: "No",
          artClasses: "N/A",
          fitness: "Yes",
          sports: "Yes",
          childCare: "Yes",
          seniorsProgram: "Yes",
          youthJustice: "No",
          dance: "Yes",
        },
        recreationAmenities: {
          swimmingPool: "No",
          skatingRink: "Yes",
          sportsPlayfields: "Yes",
          other: "N/A",
          hockeyRink: "Yes – Outdoor",
          tennisCourts: "Yes",
        },
        communityAssociationInformation: {
          federalCharityStatusRegistered: "No",
          facilityFaxNumber: "(403) 249-7811",
          facilityPhoneNumber: "(403) 249-1138",
          communityAssociationWebsite: "SCACalgary.ca",
          provincialSocietyRegisteredDate: "December 2, 1981",
          facilityLocatedat: "277 Strathcona Drive SW",
          facilityEmail: "info@SCACalgary.ca",
          provincialSocietyRegisteredName: "SCA Community Association",
        },
        cityQuadrant: "SW",
      },
  
      {
        type: "Feature",
        properties: {
          ID: 3,
          isAlien: "",
          name: "Bankview Community Association",
          img: "src/images/halls/CH3.jpeg",
          address: "2418 17 St SW, Calgary, AB T2T 4M8, Canada",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1040631, 51.0325128],
        },
        programs: {
          sports: "No",
          fitness: "No",
          childCare: "No",
          seniorsProgram: "No",
          artClasses: "N/A",
          bingo: "No",
          dance: "No",
          youthJustice: "No",
        },
        communityAssociationFacilities: {
          gamesRoom: "No",
          gym: "No",
          soundSystem: "Yes",
          lounge: "No",
          indoorFireplace: "No",
          stage: "No",
          wheelchairAccess: "Yes",
          mainHallLicensedCapacity: "125",
          meetingRooms: "Yes",
          kitchen: "Yes – Standard",
          outdoorBBQ: "Yes",
        },
        communityAssociationInformation: {
          federalCharityStatusRegistered: "No",
          facilityLocatedat: "2418 - 17 Street SW",
          provincialSocietyRegisteredDate: "December 20, 1954",
          communityAssociationWebsite: "bankview.org",
          facilityPhoneNumber: "(403) 244-2544",
          facilityEmail: "N/A",
          facilityFaxNumber: "NA",
          provincialSocietyRegisteredName: "Bankview Community Association",
        },
        recreationAmenities: {
          swimmingPool: "No",
          sportsPlayfields: "Playground",
          hockeyRink: "No",
          skatingRink: "Yes",
          other: "N/A",
          tennisCourts: "No",
        },
        cityQuadrant: "SW",
        communityAssociationBoundaries: {
          west: "19 Street; 19A Street (through to 26 Avenue)",
          north: "17 Avenue",
          east: "14 Street",
          south: "26 Avenue",
        },
      },
  
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Palliser Bayview Pumphill Community Association",
          img: "src/images/halls/CH4.jpeg",
          address: "2323 Palliser Dr SW, Calgary, AB T2V 3S4, Canada",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1161444, 50.968834],
        },
        communityAssociationInformation: {
          federalCharityStatusRegistered: "Yes",
          communityAssociationWebsite: "pbpcommunity.ca",
          provincialSocietyRegisteredDate: "September 23, 1970",
          facilityFaxNumber: "NA",
          communityAssociationGeneralEmail: "pbpcam@pbpcommunity.ca",
          facilityPhoneNumber: "(403) 281-1908",
          facilityLocatedat: "2323 Palliser Drive SW",
          provincialSocietyRegisteredName:
            "Palliser-Bayview-Pump Hill Community Association",
        },
        communityAssociationBoundaries: {
          east: "14 Street",
          north: "Glenmore Reservoir; Heritage Drive",
          south: "Southland Drive",
          west: "24 Street",
        },
        programs: {
          fitness: "No",
          artClasses: "N/A",
          sports: "Yes",
          childCare: "Preschool, ages 2-5",
          seniorsProgram: "No",
          bingo: "No",
          dance: "No",
          youthJustice: "No",
        },
        communityAssociationName:
          "Palliser – Bayview – Pumphill Community Association",
        communityAssociationFacilities: {
          mainHallLicensedCapacity: "109",
          outdoorBBQ: "No",
          stage: "No",
          gym: "No",
          meetingRooms: "Yes",
          gamesRoom: "No",
          kitchen: "Yes – Standard",
          soundSystem: "No",
          lounge: "No",
          indoorFireplace: "No",
          wheelchairAccess: "Yes",
        },
        recreationAmenities: {
          hockeyRink: "No",
          tennisCourts: "No",
          other: "N/A",
          swimmingPool: "No",
          sportsPlayfields: "Yes",
          skatingRink: "Yes – Outdoor",
        },
        cityQuadrant: "SW",
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Bridgeland-Riverside Community Association",
          img: "",
          address: "917 Centre Ave NE, Calgary, AB T2E 0C6",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        communityAssociationFacilities: {
          stage: "NA",
          meetingRooms: "Yes",
          kitchen: "Yes",
          mainHallLicensedCapacity: "115",
          lounge: "No",
          gym: "No",
          wheelchairAccess: "Yes",
          soundSystem: "NA",
          gamesRoom: "No",
          indoorFireplace: "NA",
          outdoorBBQ: "NA",
        },
        communityAssociationBoundaries: {
          east: "Nose Creek",
          south: "Bow River",
          west: "1 Street",
          north: "7 Avenue; 9A Street; 8 Avenue",
        },
        recreationAmenities: {
          swimmingPool: "No",
          skatingRink: "No",
          tennisCourts: "No",
          hockeyRink: "No",
          sportsPlayfields: "Yes",
          other: "N/A",
        },
        programs: {
          youthJustice: "No",
          dance: "No",
          bingo: "No",
          artClasses: "No",
          sports: "Yes",
          childCare: "No",
          seniorsProgram: "No",
          fitness: "No",
        },
        cityQuadrant: "NE",
        communityAssociationInformation: {
          facilityFaxNumber: "No",
          federalCharityStatusRegistered: "No",
          provincialSocietyRegisteredDate: "August 12, 1950",
          provincialSocietyRegisteredName:
            "Bridgeland-Riverside Community Association",
          communityAssociationWebsite: "brcacalgary.org",
          communityAssociationGeneralEmail: "No",
          facilityPhoneNumber: "(403) 263-5755",
          facilityLocatedat: "917 Centre Ave NE  ",
        },
        communityAssociationName: "Bridgeland-Riverside Community Association",
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Braeside Community Association",
          img: "",
          address: "1024 Braeside Dr SW, Calgary, AB T2W 6G5",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        programs: {
          dance: "No",
          fitness: "No",
          youthJustice: "Yes",
          bingo: "No",
          childCare: "Yes",
          seniorsProgram: "Yes",
          artClasses: "Yes",
          sports: "No",
        },
        communityAssociationBoundaries: {
          south: "Anderson Road",
          east: "14 Street",
          west: "24 Street",
          north: "Southland Drive",
        },
        communityAssociationName: "Braeside Community Association",
        cityQuadrant: "SW",
        communityAssociationInformation: {
          communityAssociationGeneralEmail: "NA",
          provincialSocietyRegisteredDate: "August 23, 1967",
          facilityFaxNumber: "(403) 253-3528",
          provincialSocietyRegisteredName: "The Braeside Community Association",
          facilityLocatedat: "11024 Braeside Drive SW",
          communityAssociationWebsite: "NA",
          facilityPhoneNumber: "(403) 253-4232",
          federalCharityStatusRegistered: "No",
        },
        recreationAmenities: {
          skatingRink: "Yes – Outdoor",
          tennisCourts: "No",
          other: "Basketball Courts",
          hockeyRink: "Yes – Outdoor",
          swimmingPool: "No",
          sportsPlayfields: "Yes",
        },
        communityAssociationFacilities: {
          wheelchairAccess: "Yes",
          gamesRoom: "No",
          meetingRooms: "Yes (Capacity: 25-75)",
          gym: "No",
          indoorFireplace: "No",
          lounge: "No",
          stage: "Yes",
          soundSystem: "Yes",
          outdoorBBQ: "No",
          kitchen: "Yes – Standard",
          mainHallLicensedCapacity: "240",
        },
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Hounsfield Heights – Briar Hill Community Association",
          img: "",
          address: "1928 14 Ave NW, Calgary, AB T2N 1M5",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        recreationAmenities: {
          sportsPlayfields: "No",
          swimmingPool: "No",
          tennisCourts: "No",
          skatingRink: "Yes – Outdoor",
          other: "N/A",
          hockeyRink: "No",
        },
        programs: {
          childCare: "Yes",
          dance: "No",
          youthJustice: "No",
          sports: "Yes",
          artClasses: "N/A",
          fitness: "No",
          bingo: "No",
          seniorsProgram: "Yes",
        },
        communityAssociationName:
          "Hounsfield Heights – Briar Hill Community Association",
        communityAssociationInformation: {
          communityEmail: "admin@hh-bh.ca",
          provincialSocietyRegisteredName:
            "Hounsfield HeightsBriar Hill Community Association",
          facilityLocatedat: "1922 - 14 Avenue NW",
          communityAssociationWebsite: "hh-bh.ca",
          provincialSocietyRegisteredDate: "August 28, 1953",
          federalCharityStatusRegistered: "No",
          facilityFaxNumber: "N/A",
          facilityPhoneNumber: "(403) 282-6634",
        },
        communityAssociationBoundaries: {
          west: "Crowchild Trail; 12 Avenue; Juniper Road; 22 Street",
          north: "16 Avenue",
          south: "Lane north of 7 Avenue to 19 Street; 8 Avenue",
          east: "14 Street",
        },
        communityAssociationFacilities: {
          gym: "Yes",
          outdoorBBQ: "No",
          kitchen: "Yes",
          mainHallLicensedCapacity: "100",
          lounge: "No",
          indoorFireplace: "No",
          gamesRoom: "No",
          stage: "No",
          meetingRooms: "Yes (Capacity: 25)",
          soundSystem: "No",
          wheelchairAccess: "Yes",
        },
        cityQuadrant: "NW",
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Bowness Community Association",
          img: "",
          address: "7904 43 Ave NW, Calgary, AB T3B 4P9",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        recreationAmenities: {
          tennisCourts: "No",
          skatingRink: "Yes – Indoor",
          other: "N/A",
          hockeyRink: "Yes",
          swimmingPool: "No",
          sportsPlayfields: "Yes",
        },
        communityAssociationBoundaries: {
          north: "Bow River",
          east: "Bow River",
          west: "101 Street",
          south: "16 Avenue; Sarcee Trail; Edworthy Park",
        },
        communityAssociationFacilities: {
          gamesRoom: "No",
          gym: "No",
          outdoorBBQ: "No",
          mainHallLicensedCapacity: "935",
          indoorFireplace: "No",
          kitchen: "Yes – Commercial",
          meetingRooms: "Yes",
          stage: "No",
          wheelchairAccess: "Main floor only",
          lounge: "No",
          soundSystem: "No",
        },
        communityAssociationInformation: {
          facilityPhoneNumber: "(403) 288-8300",
          provincialSocietyRegisteredDate: "N/A",
          federalCharityStatusRegistered: "N/A",
          facilityFaxNumber: "(403) 288-8307",
          provincialSocietyRegisteredName: "Bowness Community Association",
          communityEmail: "N/A",
          communityAssociationWebsite: "mybowness.com",
          facilityLocatedat: "Facility operated by the City of Calgary",
        },
        programs: {
          artClasses: "N/A",
          dance: "No",
          fitness: "No",
          youthJustice: "No",
          bingo: "No",
          sports: "No",
          childCare: "No",
          seniorsProgram: "No",
        },
        cityQuadrant: "NW",
        communityAssociationName: "Bowness Community Association",
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Cambrian Heights Community Association",
          img: "",
          address: "600 Northmount Dr NW, Calgary, AB T2K 3J5",
        },
        geometry: {
            type: "Point",
            coordinates: [-114.1825231, 51.0472992],
          },
        programs: {
          sports: "No",
          dance: "No",
          fitness: "Yes",
          bingo: "No",
          artClasses: "N/A",
          childCare: "Yes",
          youthJustice: "Yes",
          seniorsProgram: "No",
        },
        recreationAmenities: {
          hockeyRink: "No",
          tennisCourts: "No",
          swimmingPool: "No",
          sportsPlayfields: "Yes",
          other: "N/A",
          skatingRink: "Yes – Outdoor",
        },
        communityAssociationName: "Cambrian Heights Community Association",
        cityQuadrant: "NW",
        communityAssociationFacilities: {
          gamesRoom: "No",
          indoorFireplace: "No",
          kitchen: "Yes – Commercial",
          outdoorBBQ: "No",
          gym: "Yes",
          meetingRooms: "Yes",
          stage: "No",
          mainHallLicensedCapacity: "150",
          soundSystem: "No",
          wheelchairAccess: "Yes",
          lounge: "No",
        },
        communityAssociationInformation: {
          provincialSocietyRegisteredDate: "March 5, 1958",
          provincialSocietyRegisteredName:
            "The Cambrian Heights Community Association",
          communityEmail: "CHCA_Hall@telus.net",
          communityWebsite: "cambrianheightscommunity.com",
          facilityFaxNumber: "N/A",
          facilityPhoneNumber: "(403) 284-1175 for facility rentals",
          facilityLocatedat: "600 Northmount Drive NW",
          federalCharityStatusRegistered: "No",
        },
        communityAssociationBoundaries: {
          south: "Northmount Drive; Cambrian Drive",
          east: "9 Street; 38 Avenue (both sides); 10 Street; 32 Avenue; Confederation Park",
          west: "14 Street",
          north: "John Laurie Boulevard: 40 Avenue",
        },
      },
      {
        type: "Feature",
        properties: {
          ID: 4,
          isAlien: "",
          name: "Calgary Marlborough Community Association",
          img: "",
          address: "636 Marlborough Way NE Calgary, AB T2A 4L2",
        },
        geometry: {
            type: "Point",
            coordinates: [-114.1825231, 51.0472992],
          },
        recreationAmenities: {
          other: "N/A",
          skatingRink: "No",
          swimmingPool: "No",
          tennisCourts: "No",
          sportsPlayfields: "Yes",
          hockeyRink: "No",
        },
        programs: {
          childCare: "No",
          fitness: "Yes",
          bingo: "Yes",
          seniorsProgram: "Yes",
          sports: "Yes",
          artClasses: "No",
          dance: "No",
          youthJustice: "No",
        },
        communityAssociationFacilities: {
          soundSystem: "Yes",
          outdoorBBQ: "yes",
          kitchen: "Yes",
          stage: "Yes",
          lounge: "Yes",
          gamesRoom: "No",
          gym: "yes",
          meetingRooms: "Yes",
          indoorFireplace: "yes",
          mainHallLicensedCapacity: "400",
          wheelchairAccess: "yes",
        },
        communityAssociationName: "Calgary Marlborough Community Association",
        cityQuadrant: "NE",
        communityAssociationInformation: {
          facilityLocatedat: "636 Marlborough Way NE",
          facilityPhoneNumber: "403-273-5894",
          communityAssociationGeneralEmail: "info@calgarymarlborough.com",
          provincialSocietyRegisteredName:
            "Calgary Marlborough Community Association",
          communityAssociationWebsite: "calgarymarlborough.com",
          facilityFaxNumber: "No",
          federalCharityStatusRegistered: "No",
          provincialSocietyRegisteredDate: "April 10, 1970",
        },
        communityAssociationBoundaries: {
          south: "Memorial Dr",
          north: "16 Ave",
          east: "52 Street",
          west: "36 Street",
        },
      },
      {
        type: "Feature",
        properties: {
          ID: 2,
          isAlien: "",
          name: "Brentwood Community Association",
          img: "src/images/halls/CH2.jpeg",
          address: "1520 Northmount Dr NW, Calgary, AB T2L 0G6",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        programs: {
          sports: "Yes",
          childCare: "No",
          youthJustice: "No",
          artClasses: "N/A",
          fitness: "No",
          bingo: "No",
          dance: "No",
          seniorsProgram: "Yes",
        },
        recreationAmenities: {
          hockeyRink: "No",
          other: "N/A",
          sportsPlayfields: "Yes – Soccer",
          tennisCourts: "No",
          swimmingPool: "No",
          skatingRink: "Yes – IndoorOutdoor",
        },
        communityAssociationBoundaries: {
          north: "John Laurie Boulevard",
          south: "Crowchild Trail",
          east: "Charleswood Drive; 26 Street; Northmount Drive; Brantford Drive; Brentwood Boulevard",
          west: "Shaganappi Trail",
        },
        cityQuadrant: "NW",
        communityAssociationName: "Brentwood Community Association",
        communityAssociationFacilities: {
          gym: "No",
          lounge: "No",
          stage: "No",
          wheelchairAccess: "Yes",
          gamesRoom: "No",
          outdoorBBQ: "No",
          indoorFireplace: "No",
          soundSystem: "Yes",
          mainHallLicensedCapacity: "130",
          meetingRooms: "Yes",
          kitchen: "Yes – Commercial",
        },
        communityAssociationInformation: {
          communityEmail: "N/A",
          facilityFaxNumber: "(403) 284-3951",
          communityAssociationWebsite: "brentwoodcommunity.com",
          facilityPhoneNumber: "(403) 284-3477",
          provincialSocietyRegisteredDate: "December 18, 1963",
          provincialSocietyRegisteredName: "Brentwood Community Association",
          federalCharityStatusRegistered: "No",
          facilityLocatedat: "Brentwood Sportsplex: 1520B Northmount Drive NW",
        },
      },
      {
        type: "Feature",
        properties: {
          ID: 2,
          isAlien: "",
          name: "Abbeydale Community Association",
          img: "src/images/halls/CH2.jpeg",
          address: "821 Abbeydale Dr NE, Calgary, AB T2A 6N7",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        communityAssociationInformation: {
          facilityLocatedat: "821 Abbeydale Drive NE",
          provincialSocietyRegisteredDate: "March 22, 1979",
          facilityPhoneNumber: "(403) 248-2229",
          communityAssociationGeneralEmail: "hallmanager@abbeydaleca.com",
          communityAssociationWebsite: "abbeydaleca.com",
          federalCharityStatusRegistered: "No",
          provincialSocietyRegisteredName: "Abbeydale Community Association",
          facilityFaxNumber: "(403) 248-2880",
        },
        communityAssociationBoundaries: {
          east: "East Freeway",
          south: "CNR mainline",
          north: "16 Avenue",
          west: "68 Street",
        },
        cityQuadrant: "NE",
        recreationAmenities: {
          swimmingPool: "No",
          hockeyRink: "Yes",
          sportsPlayfields: "Yes",
          tennisCourts: "Yes",
          other: "N/A",
          skatingRink: "Yes",
        },
        communityAssociationFacilities: {
          mainHallLicensedCapacity: "170",
          stage: "No",
          indoorFireplace: "Yes",
          lounge: "Yes",
          gym: "No",
          gamesRoom: "No",
          kitchen: "Yes",
          wheelchairAccess: "Yes",
          outdoorBBQ: "No",
          soundSystem: "No",
          meetingRooms: "Yes",
        },
        programs: {
          dance: "Yes",
          sports: "Yes",
          artClasses: "No",
          bingo: "No",
          fitness: "No",
          youthJustice: "No",
          childCare: "Yes",
          seniorsProgram: "No",
        },
        communityAssociationName: "Abbeydale Community Association",
      },
      {
        type: "Feature",
        properties: {
          ID: 2,
          isAlien: "",
          name: "Temple Community Association",
          img: "src/images/halls/CH2.jpeg",
          address: "167 Templegreen Rd NE, Calgary, AB T1Y 6G3",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        programs: {
          bingo: "No",
          sports: "Yes",
          seniorsProgram: "No",
          artClasses: "No",
          childCare: "Yes",
          youthJustice: "Yes",
          fitness: "Yes",
          dance: "Yes",
        },
        communityAssociationName: "Temple Community Association",
        recreationAmenities: {
          hockeyRink: "Yes",
          skatingRink: "Yes",
          swimmingPool: "No",
          other: "N/A",
          tennisCourts: "Yes",
          sportsPlayfields: "Yes",
        },
        cityQuadrant: "NE",
        communityAssociationBoundaries: {
          north: "McKnight Boulevard",
          south: "32 Avenue",
          west: "52 Street",
          east: "68 Street",
        },
        communityAssociationFacilities: {
          indoorFireplace: "No",
          gamesRoom: "No",
          gym: "No",
          kitchen: "Yes",
          meetingRooms: "Yes",
          lounge: "No",
          mainHallLicensedCapacity: "250",
          stage: "Yes",
          outdoorBBQ: "No",
          wheelchairAccess: "Yes",
          soundSystem: "Yes",
        },
        communityAssociationInformation: {
          provincialSocietyRegisteredName: "Temple Community Association",
          federalCharityStatusRegistered: "No",
          facilityLocatedat: "167 Templegreen RD NE",
          communityAssociationWebsite: "templecalgary.ca",
          facilityFaxNumber: "(403) 293-5441",
          communityAssociationGeneralEmail: "temp11@telus.net",
          provincialSocietyRegisteredDate: "October 26, 1978",
          facilityPhoneNumber: "403-280-5466",
        },
      },
      {
        type: "Feature",
        properties: {
          ID: 2,
          isAlien: "",
          name: "Banff Trail Community Association",
          img: "src/images/halls/CH2.jpeg",
          address: "2115 20 AVE, Calgary, AB T2M 1J1",
        },
        geometry: {
          type: "Point",
          coordinates: [-114.1825231, 51.0472992],
        },
        cityQuadrant: "NW",
        communityAssociationName: "Banff Trail Community Association",
        communityAssociationFacilities: {
          wheelchairAccess: "Yes",
          outdoorBBQ: "No",
          kitchen: "Yes – Standard",
          lounge: "No",
          indoorFireplace: "No",
          stage: "No",
          gym: "No",
          mainHallLicensedCapacity: "91",
          gamesRoom: "No",
          soundSystem: "Yes",
          meetingRooms: "Yes",
        },
        communityAssociationInformation: {
          federalCharityStatusRegistered: "No",
          communityAssociationWebsite: "banfftrailcommunity.ca",
          facilityPhoneNumber: "(403) 282-2234",
          provincialSocietyRegisteredName: "Banff Trail Community Association",
          provincialSocietyRegisteredDate: "August 29, 1955",
          facilityFaxNumber: "None",
          facilityLocatedat: "2115 - 20 Avenue NW",
          communityEmail: "N/A",
        },
        recreationAmenities: {
          swimmingPool: "No",
          hockeyRink: "No",
          tennisCourts: "No",
          skatingRink: "Yes – Outdoor",
          other: "N/A",
          sportsPlayfields: "Yes",
        },
        programs: {
          dance: "Yes",
          fitness: "No",
          childCare: "No",
          artClasses: "N/A",
          bingo: "No",
          sports: "Outdoor Soccer",
          seniorsProgram: "Yes",
          youthJustice: "No",
        },
        communityAssociationBoundaries: {
          east: "19 Street; 24 Avenue; 18 Street",
          west: "Crowchild Trail",
          north: "Morley Trail; Cochrane Road; Canmore Road",
          south: "16 Avenue",
        },
      },
    ],
  };
  